import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  header: {
    padding: 20,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
    letterSpacing: 0.5,
  },
  dateText: {
    fontSize: 16,
    color: "#666",
    marginTop: 5,
    fontWeight: "500",
  },
  classSelector: {
    backgroundColor: "#6664",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    display: "flex",
    flexDirection: "row",
  },
  classButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginHorizontal: 5,
    borderRadius: 20,
    backgroundColor: "#f0f0f0",
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    height: 40,
  },
  selectedClassButton: {
    backgroundColor: "#4a69bd",
    elevation: 3,
    shadowColor: "#4a69bd",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  classButtonText: {
    fontSize: 16,
    color: "#666",
    fontWeight: "500",
  },
  selectedClassText: {
    color: "#fff",
    fontWeight: "600",
  },
  studentList: {
    flex: 1,
    padding: 15,
  },
  studentRow: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  studentInfo: {
    flex: 1,
    paddingRight: 10,
  },
  studentName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    letterSpacing: 0.3,
  },
  rollNo: {
    fontSize: 14,
    color: "#666",
    marginTop: 2,
    fontWeight: "400",
  },
  attendanceButtons: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  statusButton: {
    padding: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ddd",
    backgroundColor: "#fff",
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  presentButton: {
    backgroundColor: "#4CAF50",
    borderColor: "#4CAF50",
    elevation: 2,
    shadowColor: "#4CAF50",
  },
  lateButton: {
    backgroundColor: "#FFC107",
    borderColor: "#FFC107",
    elevation: 2,
    shadowColor: "#FFC107",
  },
  absentButton: {
    backgroundColor: "#F44336",
    borderColor: "#F44336",
    elevation: 2,
    shadowColor: "#F44336",
  },
  submitButton: {
    backgroundColor: "#4a69bd",
    margin: 15,
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    elevation: 3,
    shadowColor: "#4a69bd",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  submitButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  reportContainer: {
    backgroundColor: "#fff",
    margin: 15,
    marginTop: 5,
    padding: 15,
    borderRadius: 10,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  reportTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 10,
    letterSpacing: 0.3,
  },
  reportRow: {
    marginVertical: 5,
    padding: 10,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
  },
  reportDate: {
    fontSize: 14,
    color: "#666",
    marginBottom: 5,
    fontWeight: "500",
  },
  reportStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5,
  },
  reportStat: {
    fontSize: 12,
    fontWeight: "600",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: "#fff",
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  presentStat: {
    color: "#4CAF50",
    backgroundColor: "#E8F5E9",
  },
  lateStat: {
    color: "#FFC107",
    backgroundColor: "#FFF8E1",
  },
  absentStat: {
    color: "#F44336",
    backgroundColor: "#FFEBEE",
  },
  searchContainer: {
    padding: 15,
    paddingBottom: 5,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  searchInput: {
    backgroundColor: "#f5f5f5",
    padding: 10,
    borderRadius: 8,
    fontSize: 14,
    color: "#333",
  },
  noDataText: {
    textAlign: "center",
    fontSize: 16,
    color: "#666",
    marginTop: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    color: "#F44336",
    textAlign: "center",
    margin: 10,
    fontSize: 14,
  },
});
